name       : haskell-persistent-template
version    : 2.5.2
release    : 1
source     :
    - http://hackage.haskell.org/package/persistent-template-2.5.2/persistent-template-2.5.2.tar.gz : de695b008158f9ae66d103fc33f89c098ebcf59337367063d9f4f816a58b4011
license    : MIT
component  : programming.haskell
summary    : Provides Template Haskell helpers for persistent.
description: |
    Provides Template Haskell helpers for persistent.
builddeps  :
    - haskell-aeson-compat
    - haskell-cabal-install
    - haskell-nats
    - haskell-persistent
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
