name       : haskell-persistent-template
version    : 2.6.0
release    : 3
source     :
    - https://hackage.haskell.org/package/persistent-template-2.6.0/persistent-template-2.6.0.tar.gz : 5bfa8cbe7c25bdef33cc6d6ece1673f847c2a56860f57c69d8d2d0ecacf82173
license    : MIT
component  : programming.haskell
summary    : Provides Template Haskell helpers for persistent.
description: |
    Provides Template Haskell helpers for persistent.
builddeps  :
    - haskell-aeson-compat-devel
    - haskell-cabal-install
    - haskell-persistent-devel
rundeps    :
    - devel:
        - haskell-aeson-compat-devel
        - haskell-persistent-devel
networking : yes
setup      : |
    sed -i "s|< 1.5|< 1.6|" persistent-template.cabal # aeson
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
