name       : haskell-persistent-template
version    : 2.5.4
release    : 2
source     :
    - http://hackage.haskell.org/package/persistent-template-2.5.4/persistent-template-2.5.4.tar.gz : 4cae740ce92f98cb3ae9e092e740753394d5687b887399ee5f87af7f3c730a01
license    : MIT
component  : programming.haskell
summary    : Provides Template Haskell helpers for persistent.
description: |
    Provides Template Haskell helpers for persistent.
builddeps  :
    - haskell-aeson-compat
    - haskell-cabal-install
    - haskell-persistent
networking : yes
setup      : |
    sed -i "s|< 1.3|< 1.4|" persistent-template.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
